version: '2'
services:
  web:
    stdin_open: true
    tty: true
    entrypoint: ./entrypoint.sh
    build: .
    environment:
      - PORT: 3000
    ports:
     - "3000:3000"
    volumes:
     - .:/var/app
